name: Docker Image CI for GHCR

on:
  release:
    types: [created]

jobs:
  build_and_publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Get package.json version
      id: package-version
      run: |
        PKG_VERSION=$(jq -r .version package.json)
        echo "PKG_VERSION=$PKG_VERSION" >> $GITHUB_ENV
    - name: Verify version match
      run: |
        TAG_VERSION="${RELEASE_VERSION#v}"  
        if [ "$TAG_VERSION" != "$PKG_VERSION" ]; then
          echo "Error: Tag version $RELEASE_VERSION does not match package.json version $PKG_VERSION"
          exit 1
        fi
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Build and push the image
      run: |
        docker login --username classinsights --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
        docker build --tag ghcr.io/classinsights/dashboard:$RELEASE_VERSION --tag ghcr.io/classinsights/dashboard:latest .
        docker push ghcr.io/classinsights/dashboard --all-tags